main: me.flail.FishyDispensers.FishyDispensers
name: FishyDispensers
author: FlailoftheLord
version: 1.1
description: customizable dispensers

commands:
  fishydispensers:
    usage: /fishydispensers [get:reload]
    description: use the fishy dispensers
    aliases: [fdispenser, fdispensers, fishyd, fdis, fd]
    
permissions:
  fishydispensers.command:
    description: use the command
    default: op