main: me.flail.FishyDispensers.FishyDispensers
name: FishyDispensers
author: FlailoftheLord
version: 1.5
description: customizable infinite dispensers

commands:
  fishydispensers:
    usage: /fishydispensers [get:reload]
    description: use the fishy dispensers
    aliases: [dispenser, fd]
    
permissions:
  fishydispensers.command:
    description: use the command
    default: false